server:
  port: 8066
  custom:
    # http 端口
    httpPort: 8065

spring:
  profiles:
    active: jinyu
  application:
    name: jinyu


nacos:
  config:
    # nacos
    server-addr: 47.74.48.135:8848
    data-ids: jinyu,jinyu-bs,jinyu-sms,jinyu-ocr,jinyu-mobile,jinyu-oss,jinyu-fk,jinyu-pay
    type: YAML
    auto-refresh: true
    namespace: 4e0692f0-7692-4701-b4d3-087b29d50ebf
    bootstrap:
      enable: true

#    ext-config:
#      - server-addr: 8.210.166.87:82 # Nacos 服务器地址
#        data-id: dev-sms # 使用的 Nacos 配置集的 dataId。
#        # data-ids: dev-sms
#        type: properties # 使用的 Nacos 配置集的配置格式。默认为 PROPERTIES。
#        namespace: a31478cc-37f4-48e6-a75f-c3dede11eb03 # 使用的 Nacos 的命名空间，默认为 null。
#        auto-refresh: true # 是否自动刷新，默认为 false。
#        bootstrap:
#          enable: true
    #      - # 这里，可以继续添加。
