server:
  port: 8055
  custom:
    # http 端口
    httpPort: 8054

spring:
  profiles:
    active: jiubafenqi
  application:
    name: jiubafenqi


nacos:
  config:
    # nacos
    server-addr: 47.74.48.135:8848
    data-ids: jiubafenqi,jiubafenqi-bs,jiubafenqi-sms,jiubafenqi-ocr,jiubafenqi-mobile,jiubafenqi-oss,jiubafenqi-fk,jiubafenqi-pay
    type: YAML
    auto-refresh: true
    namespace: 08f0daba-7e88-4b9c-bad8-3692134ba692
    bootstrap:
      enable: true

#    ext-config:
#      - server-addr: 8.210.166.87:82 # Nacos 服务器地址
#        data-id: dev-sms # 使用的 Nacos 配置集的 dataId。
#        # data-ids: dev-sms
#        type: properties # 使用的 Nacos 配置集的配置格式。默认为 PROPERTIES。
#        namespace: a31478cc-37f4-48e6-a75f-c3dede11eb03 # 使用的 Nacos 的命名空间，默认为 null。
#        auto-refresh: true # 是否自动刷新，默认为 false。
#        bootstrap:
#          enable: true
    #      - # 这里，可以继续添加。
