server:
  port: 8084
  custom:
    # http 端口
    httpPort: 8074

spring:
  profiles:
    active: youqianjie
  application:
    name: youqianjie


nacos:
  config:
    # nacos
    server-addr: 47.74.48.135:8848
    data-ids: youqianjie,youqianjie-bs,youqianjie-sms,youqianjie-ocr,youqianjie-mobile,youqianjie-oss,youqianjie-fk,youqianjie-pay
    type: YAML
    auto-refresh: true
    namespace: c42c868f-32b3-42b9-98e1-fec23a3da457
    bootstrap:
      enable: true

#    ext-config:
#      - server-addr: 8.210.166.87:82 # Nacos 服务器地址
#        data-id: dev-sms # 使用的 Nacos 配置集的 dataId。
#        # data-ids: dev-sms
#        type: properties # 使用的 Nacos 配置集的配置格式。默认为 PROPERTIES。
#        namespace: a31478cc-37f4-48e6-a75f-c3dede11eb03 # 使用的 Nacos 的命名空间，默认为 null。
#        auto-refresh: true # 是否自动刷新，默认为 false。
#        bootstrap:
#          enable: true
    #      - # 这里，可以继续添加。
