server:
  port: 8088
  custom:
    # http 端口
    httpPort: 8087

spring:
  profiles:
    active: dev
  application:
    name: dev

nacos:
  config:
    # nacos
    server-addr: 47.74.48.135:8848
    data-ids: dev,dev-bs,dev-sms,dev-ocr,dev-mobile,dev-oss,dev-fk,dev-pay
    type: YAML
    auto-refresh: true
    namespace: 9014ff48-2c98-4ba1-b7cf-2dc3e4169fc6
    bootstrap:
      enable: true

#    ext-config:
#      - server-addr: 8.210.166.87:82 # Nacos 服务器地址
#        data-id: dev-sms # 使用的 Nacos 配置集的 dataId。
#        # data-ids: dev-sms
#        type: properties # 使用的 Nacos 配置集的配置格式。默认为 PROPERTIES。
#        namespace: a31478cc-37f4-48e6-a75f-c3dede11eb03 # 使用的 Nacos 的命名空间，默认为 null。
#        auto-refresh: true # 是否自动刷新，默认为 false。
#        bootstrap:
#          enable: true
    #      - # 这里，可以继续添加。
